name: hw7env

channels:
  - conda-forge

dependencies:
  - python=3.9.9

  - contextily=1.1.0
  - geopandas=0.10.2
  - h5py=3.6.0
  - ipykernel=6.7.0
  - lxml=4.6.3
  - matplotlib=3.5.1
  - matplotlib-inline=0.1.3
  - numpy=1.21.5
  - pandas=1.3.5
  - scikit-image=0.19.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - statsmodels=0.13.1
  - sympy=1.9
  - jupyter-book==0.12.1
  - jupyter-sphinx==0.3.2
  - markdown-it-py==1.1.0
  - markupsafe==2.0.1
  - myst-nb==0.13.1
  - myst-parser==0.15.2
  - sphinx==4.4.0
  - sphinx-jupyterbook-latex==0.4.6
  - pip
  - pip:
    - -r requirements.txt
  